"""add details and care_instructions to product

Revision ID: 1ce7411b5fd9
Revises: 27520f78ccaa
Create Date: 2026-08-06 18:01:48.709544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce7411b5fd9'
down_revision = '27520f78ccaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('care_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('care_instructions')
        batch_op.drop_column('details')

    # ### end Alembic commands ###
