"""Add buyer, recipient and status fields to GiftCard

Revision ID: 27520f78ccaa
Revises: fbb521ed6e95
Create Date: 2026-08-02 19:39:44.989622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27520f78ccaa'
down_revision = 'fbb521ed6e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyer_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('gift_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['buyer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('gift_message')
        batch_op.drop_column('recipient_email')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('buyer_email')
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###
