"""Add features column to membership_tiers

Revision ID: 4ebc1aa9abfc
Revises: a42ba4f066bf
Create Date: 2026-08-02 03:27:35.200310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ebc1aa9abfc'
down_revision = 'a42ba4f066bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_tiers', schema=None) as batch_op:
        batch_op.alter_column('features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_tiers', schema=None) as batch_op:
        batch_op.alter_column('features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
