"""add_r1_models_and_settings_seed

Revision ID: a42ba4f066bf
Revises: 54afcbd02d2c
Create Date: 2026-07-30 17:44:33.595853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42ba4f066bf'
down_revision = '54afcbd02d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('donated_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period')
    )
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('membership_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('spend_threshold', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loyalty_points_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('min_order_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('qualifying_order_id', sa.Integer(), nullable=True),
    sa.Column('reward_issued', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qualifying_order_id'], ['order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_users_referral_code', ['referral_code'])
        batch_op.create_foreign_key('fk_users_referred_by_id', 'users', ['referred_by_id'], ['id'], ondelete='SET NULL')

    # Seed default settings
    setting_table = sa.table(
        'setting',
        sa.column('key', sa.String),
        sa.column('value', sa.Text)
    )
    op.bulk_insert(setting_table, [
        {'key': 'points_per_egp', 'value': '1'},
        {'key': 'points_to_egp_rate', 'value': '10'},
        {'key': 'review_bonus_points', 'value': '50'},
        {'key': 'social_follow_bonus_points', 'value': '50'},
        {'key': 'referral_voucher_amount', 'value': '200'},
        {'key': 'referral_voucher_min_spend', 'value': '2000'},
        {'key': 'referral_min_order_amount', 'value': '2000'},
        {'key': 'points_expiry_months', 'value': '6'},
        {'key': 'voucher_expiry_months', 'value': '1'},
    ])

    # Seed default membership tiers
    membership_tier_table = sa.table(
        'membership_tiers',
        sa.column('name', sa.String),
        sa.column('spend_threshold', sa.Float),
        sa.column('sort_order', sa.Integer)
    )
    op.bulk_insert(membership_tier_table, [
        {'name': 'Bronze', 'spend_threshold': 0.0, 'sort_order': 1},
        {'name': 'Silver', 'spend_threshold': 2000.0, 'sort_order': 2},
        {'name': 'Gold', 'spend_threshold': 5000.0, 'sort_order': 3},
        {'name': 'Platinum', 'spend_threshold': 10000.0, 'sort_order': 4},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM setting WHERE key IN ("
        "'points_per_egp', 'points_to_egp_rate', 'review_bonus_points', "
        "'social_follow_bonus_points', 'referral_voucher_amount', "
        "'referral_voucher_min_spend', 'referral_min_order_amount', "
        "'points_expiry_months', 'voucher_expiry_months'"
        ")"
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_referred_by_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_referral_code', type_='unique')
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('birth_date')

    op.drop_table('referral_conversions')
    op.drop_table('loyalty_vouchers')
    op.drop_table('loyalty_points_entries')
    op.drop_table('membership_tiers')
    op.drop_table('gift_cards')
    op.drop_table('donation_records')
    # ### end Alembic commands ###
